[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.pdo",
    "php83Extensions.pdo_mysql",
    "php83Extensions.pdo_pgsql",
    "php83Extensions.pgsql",
    "php83Extensions.mbstring",
    "php83Extensions.openssl",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.ctype",
    "php83Extensions.json",
    "php83Extensions.bcmath",
    "php83Extensions.curl",
    "composer",
    "nginx",
    "php83-fpm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "mkdir -p storage/logs storage/framework/views storage/framework/sessions storage/framework/cache",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "sh start.sh"